# Generated by Django 5.0.1 on 2024-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_merge_20221022_1445'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereço',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
